site_name:           SimilarityNetworkFusion
repo_url:            https://github.com/nadavrap/SimilarityNetworkFusion.jl
site_description:    Similarity Networks Fusion
site_author:         Nadav Rappoport
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
#  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Tutorial:
  - Tutorial 1 - Simulated data: tutorials/Simulation1.md
#  - Title 2: tutorials/page2.md
#  - Title 3: tutorials/page3.md
#- Another Section:
#  - Title 1: sec2/page1.md
#  - Title 2: sec2/page2.md
#  - Title 3: sec2/page3.md
